# Generated by Django 3.2.4 on 2021-07-01 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='image',
        ),
    ]
