# Generated by Django 3.2.4 on 2021-07-02 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0002_remove_items_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='img',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
