# Generated by Django 3.2.4 on 2021-07-02 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0003_items_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='img',
            new_name='imag',
        ),
    ]
