# Generated by Django 3.2.4 on 2021-07-03 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0006_auto_20210703_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagitems',
            old_name='tag',
            new_name='tagname',
        ),
        migrations.AddField(
            model_name='items',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='productoApp.tagitems'),
            preserve_default=False,
        ),
    ]
