# Generated by Django 3.2.4 on 2021-07-03 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0007_auto_20210703_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagItems',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='tagname',
            new_name='name',
        ),
    ]
