# Generated by Django 3.2.4 on 2021-07-03 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0008_auto_20210703_0010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='nametag',
        ),
    ]
