# Generated by Django 3.2.4 on 2021-07-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0009_rename_name_tag_nametag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='imag',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
