# Generated by Django 3.2.4 on 2021-07-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0010_alter_items_imag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
