# Generated by Django 3.2.4 on 2021-07-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productoApp', '0011_auto_20210704_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
    ]
