# Generated by Django 3.2.4 on 2021-07-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Moderadores',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
