# Generated by Django 3.2.4 on 2021-07-01 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeApp', '0002_auto_20210701_0109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Items',
        ),
    ]
