# Generated by Django 3.2.4 on 2021-07-04 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroApp', '0002_delete_moderadores'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
